# Scheduler jobs
# '0 */1 * * *' At minute 0 past every hour.
# '* * * * *'   At every minute.
# '0 0 * * *'   At 00:00.
# '0 9 1 * *'   1st of every month at 09:00

:concurrency: 5
:queues:
  - default
  - mailers

:scheduler:
  enabled: true
  schedule:
    notify_samples_of_new_companies:
      cron: '0 */1 * * *'
      class: SampleSchedulerJob
      enabled: false